### PR TITLE
fixing typo for fallback unc. case

### PR DESCRIPTION
**Pull request by pfs**

### CODE REVIEW

**Comment by bendavid** [comment]
From which CMSSW version is this new root version included?

**Comment by pfs** [comment]
right this may be a CMSSW-induced issue.
I have been using CMSSW_10_3_0_pre2 as Marco Cipriani recommended it
sometime ago.

Josh Bendavid <notifications@github.com> escreveu no dia terça, 8/01/2019
à(s) 15:11:

**Comment by bendavid** [comment]
Ah, I had already moved on to CMSSW_10_3_0_pre4 (and in fact this is needed for other recent features anyways)

**Comment by pfs** [comment]
I just tried in pre4 but i see a similar issue, looking better to the
TH1D/F API it looks like
GetSumw2() always returns a TArrayD * but
Set() expects a Double_t * or a Float_t * depending on whether it's a TH1D
or a TH1F

I have changed the code accordingly. In the end this was generated because
my baseline histograms are TH1F
while I guess in the helicity analysis they are all TH1D

**Comment by bendavid** [comment]
Ok that makes more sense.  Yes indeed for the helicity analysis everything is TH1D.

**Comment by pfs** [comment]
btw it looks like it's running as advertised since long :)
so far tried 60 bins with ~410 nuisances
target is 240 bins with ~1k nuisances
Throwing toys is *so much faster* than standard combine

Josh Bendavid <notifications@github.com> escreveu no dia quarta, 9/01/2019
à(s) 11:57:

**Pull request merged**
