### PR TITLE
save TH2D with correlation matrix of all parameters

### PR DESCRIPTION
**Pull request by mdunser**
this is done for the asimov and data fit, not for toys or anything else.
takes the hessian uncertainties.

### CODE REVIEW

**Comment by bendavid** [comment]
nparms was already available, so no need to define nTotPars

also, are you sure we want to store the correlation matrix rather than the full covariance matrix?

**Comment by mdunser** [comment]
nparms was already available, so no need to define nTotPars

fair enough, i didn’t read through everything to check. i’ll change it

also, are you sure we want to store the correlation matrix rather than the full covariance matrix?

maybe it’s easiest to save both. takes almost no space/time and it’s convenient.


On 29 Jun 2018, at 12:09, Josh Bendavid <notifications@github.com<mailto:notifications@github.com>> wrote:


nparms was already available, so no need to define nTotPars

also, are you sure we want to store the correlation matrix rather than the full covariance matrix?

**Comment by bendavid** [comment]
Ok, sure, happy to store both.

I think you also need to test/update a bit what happens with channel masking.  In this case you should be computing three separate correlation/covariance matrices, for each of mu, xsec, norm xsec in the appropriate loops

**Comment by mdunser** [comment]
right, i’ll have to figure that out. i didn’t really think about that yet.
i’ll work on that


On 29 Jun 2018, at 12:28, Josh Bendavid <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, sure, happy to store both.

I think you also need to test/update a bit what happens with channel masking. In this case you should be computing three separate correlation/covariance matrices, for each of mu, xsec, norm xsec in the appropriate loops

**Pull request merged**
